install.packages("ape")
install.packages("phytools")
install.packages("phylocomr")
install.packages("ade4")
install.packages("geometry")
install.packages("vegan")
install.packages("Biostrings")
library(ape)
library(brranching)
library(phytools)
library(phylocomr)
library(ade4)
library(geometry)
library(vegan)
library(FD)
library(ggplot2)
library(Biostrings)
library(ggtree)
library(tidyverse)
require(dplyr)
speciesdat2 <- read.csv("/Users/Manasee/OneDrive/Documents/brms/speciesdist.csv") %>% dplyr::distinct()
head(speciesdat2)
speciesdat3 <- speciesdat2 %>% mutate(Species=gsub(" ","_",speciesdat2$Species))
unique(speciesdat3)
write.csv(speciesdat3, file = "/Users/Manasee/OneDrive/Documents/brms/speciedist1.csv")
unique(speciesdat3)
speciesdat4 <- read.csv("/Users/Manasee/OneDrive/Documents/brms/speciesdist.csv")
head(speciesdat4)
speciesdat5 <- read.csv("/Users/Manasee/OneDrive/Documents/brms/speciedist1.csv") %>% dplyr::distinct()
head(speciesdat5)

  
tre2 <- read.tree("/Users/Manasee/OneDrive/Documents/brms/tre2.tre")
source('http://bioconductor.org/biocLite.R')
biocLite('phyloseq')
library(phyloseq)
install.packages("castor")
library(castor)
tre3 <- write_tree(tre2, append=FALSE, digits=10)
tre4 <- read_tree(tre3, include_edge_lengths = TRUE, include_node_labels = FALSE, underscores_as_blanks = FALSE, check_label_uniqueness  = TRUE)
head(tre4)
tre5 <- edit(tre4)


inv.phylo <- MCMCglmm::inverseA(tre4, nodes = "TIPS", scale = FALSE)
setdiff(inv.phylo$node.names,speciesdat5$Species)
head(inv.phylo)
class(inv.phylo)
head(inv.phylo)
inv.phylo1 <- edit(inv.phylo)
A <- solve(inv.phylo1$Ainv)
head(A)
rownames(A) <- rownames(inv.phylo$Ainv)
head(rownames(A))
install.packages("evdbayes")
library(evdbayes)


devtools::install_github("paul-buerkner/brms")
library(brms)
priorsmm <- get_prior(Foraged ~ DBH + Distance + (1 | Colony) + (1 | Species), data = speciesdat5, family = bernoulli())
head(priorsmm)

m1priors <- c(prior(student_t(3, 0, 2.5), class = "Intercept"), prior(student_t(3, 0, 2.5), class = "b"))
mixedmodel2 <- brm(Foraged ~ DBH + Distance + (1 | Colony) + (1 | Species), data = speciesdat5,family = bernoulli, cov_ranef = list(phylo = A), save_ranef = TRUE, prior = m1priors, save_all_pars = TRUE, sample_prior = TRUE, seed = 123)
model1 <- brm(Foraged ~ DBH + Distance, data = speciesdat5,family = bernoulli, prior = m1priors, cov_ranef = list(phylo = A), save_ranef = TRUE,save_all_pars = TRUE, sample_prior = TRUE,seed = 123)
model1L <- loo(model1)
model2 <- brm(Foraged ~ DBH + Distance + (1 | Colony), data = speciesdat5,family = bernoulli, prior = m1priors, cov_ranef = list(phylo = A), save_ranef = TRUE,save_all_pars = TRUE, sample_prior = TRUE,seed = 123)
model2L <- loo(model2)
model3 <- brm(Foraged ~ DBH + Distance + (1 | Species), data = speciesdat5,family = bernoulli, prior = m1priors, cov_ranef = list(phylo = A), save_ranef = TRUE,save_all_pars = TRUE, sample_prior = TRUE,seed = 123)
model3L <- loo(model3)
summary(mixedmodel2)
install.packages("loo")
library(loo)
rsamples <- speciesdat5(i=i, data=data[i,,drop=FALSE], draws=draws)
mixedmodelL <- loo(mixedmodel2)


