install.packages("ape")
install.packages("phytools")
install.packages("phylocomr")
install.packages("ade4")
install.packages("geometry")
install.packages("vegan")
install.packages("Biostrings")
library(ape)
library(ggplot)
library(brranching)
library(phytools)
library(phylocomr)
library(ade4)
library(geometry)
library(vegan)
library(FD)
library(ggplot2)
library(Biostrings)
library(ggtree)
speciesdat2 <- read.csv("/Users/Manasee/OneDrive/Documents/WinBugs/speciesdist.csv")
tre2 <- read.tree("/Users/Manasee/OneDrive/Documents/brms/tre2.txt")
source('http://bioconductor.org/biocLite.R')
biocLite('phyloseq')
library(phyloseq)
install.packages("castor")
library(castor)
tre3 <- write_tree(tre2, append=FALSE, digits=10)
tre4 <- read_tree(tre3, include_edge_lengths = TRUE, include_node_labels = FALSE, underscores_as_blanks   = FALSE, check_label_uniqueness  = TRUE)
inv.phylo <- MCMCglmm::inverseA(tre4, nodes = "TIPS", scale = FALSE)
A <- solve(inv.phylo$Ainv)
rownames(A) <- rownames(inv.phylo$Ainv)
install.packages("evdbayes")
library(evdbayes)
devtools::install_github("paul-buerkner/brms")
library(brms)
priors <- get_prior(Foraged ~ DBH + Distance + (1 | Colony) + (1 | Species), data = speciesdat2, family = bernoulli())
mixedmodel2 <- brm(Foraged ~ DBH + Distance + (1 | Colony) + (1 | Species), data = speciesdat2,family = bernoulli, cov_ranef = list(phylo = A), prior = priors, save_all_pars = TRUE, seed = 123)
mixedmodelL <- loo(mixedmodel2)
